"""initial schema

Revision ID: 04adfcf6661f
Revises:
Create Date: 2026-08-22 00:01:10.781916
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "04adfcf6661f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("story_cluster_id", sa.String(length=64), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_articles_fingerprint"), "articles", ["fingerprint"], unique=True)
    op.create_index(op.f("ix_articles_published_at"), "articles", ["published_at"], unique=False)
    op.create_index(op.f("ix_articles_source"), "articles", ["source"], unique=False)
    op.create_index(
        op.f("ix_articles_story_cluster_id"), "articles", ["story_cluster_id"], unique=False
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("articles_seen", sa.Integer(), nullable=False),
        sa.Column("articles_new", sa.Integer(), nullable=False),
        sa.Column("analyses_created", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_runs_status"), "ingestion_runs", ["status"], unique=False)
    op.create_table(
        "source_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("items_last_run", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_health_source"), "source_health", ["source"], unique=True)
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(length=160), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_watchlist_active"), "watchlist", ["active"], unique=False)
    op.create_index(op.f("ix_watchlist_symbol"), "watchlist", ["symbol"], unique=True)
    op.create_table(
        "article_symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("match_method", sa.String(length=30), nullable=False),
        sa.Column("in_title", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "symbol", name="uq_article_symbol"),
    )
    op.create_index(
        op.f("ix_article_symbols_article_id"), "article_symbols", ["article_id"], unique=False
    )
    op.create_index(op.f("ix_article_symbols_symbol"), "article_symbols", ["symbol"], unique=False)
    op.create_table(
        "impact_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_symbol_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=True),
        sa.Column("novelty", sa.Float(), nullable=True),
        sa.Column("priced_in", sa.Float(), nullable=True),
        sa.Column("impacts", sa.JSON(), nullable=False),
        sa.Column("financial_channels", sa.JSON(), nullable=False),
        sa.Column("observed_demand", sa.Text(), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column("catalysts", sa.JSON(), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.Column("falsifiers", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["article_symbol_id"], ["article_symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_impact_analyses_article_symbol_id"),
        "impact_analyses",
        ["article_symbol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_impact_analyses_created_at"), "impact_analyses", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_impact_analyses_is_current"), "impact_analyses", ["is_current"], unique=False
    )
    op.create_index(op.f("ix_impact_analyses_status"), "impact_analyses", ["status"], unique=False)
    op.create_table(
        "outcomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("baseline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("benchmark_entry", sa.Float(), nullable=False),
        sa.Column("benchmark_exit", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.Column("benchmark_return_pct", sa.Float(), nullable=False),
        sa.Column("excess_return_pct", sa.Float(), nullable=False),
        sa.Column("predicted_direction", sa.String(length=10), nullable=False),
        sa.Column("actual_direction", sa.String(length=10), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["impact_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id", "horizon", name="uq_analysis_horizon"),
    )
    op.create_index(op.f("ix_outcomes_analysis_id"), "outcomes", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_outcomes_horizon"), "outcomes", ["horizon"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outcomes_horizon"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_analysis_id"), table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index(op.f("ix_impact_analyses_status"), table_name="impact_analyses")
    op.drop_index(op.f("ix_impact_analyses_is_current"), table_name="impact_analyses")
    op.drop_index(op.f("ix_impact_analyses_created_at"), table_name="impact_analyses")
    op.drop_index(op.f("ix_impact_analyses_article_symbol_id"), table_name="impact_analyses")
    op.drop_table("impact_analyses")
    op.drop_index(op.f("ix_article_symbols_symbol"), table_name="article_symbols")
    op.drop_index(op.f("ix_article_symbols_article_id"), table_name="article_symbols")
    op.drop_table("article_symbols")
    op.drop_index(op.f("ix_watchlist_symbol"), table_name="watchlist")
    op.drop_index(op.f("ix_watchlist_active"), table_name="watchlist")
    op.drop_table("watchlist")
    op.drop_index(op.f("ix_source_health_source"), table_name="source_health")
    op.drop_table("source_health")
    op.drop_index(op.f("ix_ingestion_runs_status"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_articles_story_cluster_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_source"), table_name="articles")
    op.drop_index(op.f("ix_articles_published_at"), table_name="articles")
    op.drop_index(op.f("ix_articles_fingerprint"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
