"""Research facts, workflows, risk and versioned action validation."""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f9c23a0b617d"
down_revision: str | None = "e2b7c4a91d60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    columns = {item["name"] for item in sa.inspect(bind).get_columns("events")}
    for column in (
        sa.Column("first_disclosed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fact_time_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("financial_period", sa.String(80), nullable=True),
        sa.Column("fact_source_url", sa.Text(), nullable=True),
    ):
        if column.name not in columns:
            op.add_column("events", column)
    # ### commands auto generated by Alembic - please adjust! ###
    if not sa.inspect(bind).has_table("portfolio_risk_profiles"):
        op.create_table(
            "portfolio_risk_profiles",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("total_value", sa.Float(), nullable=True),
            sa.Column("available_cash", sa.Float(), nullable=True),
            sa.Column("currency", sa.String(length=8), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if not sa.inspect(bind).has_table("action_decision_snapshots"):
        op.create_table(
            "action_decision_snapshots",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("horizon", sa.Integer(), nullable=False),
            sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
            sa.Column("policy_version", sa.String(length=100), nullable=False),
            sa.Column("market", sa.String(length=8), nullable=False),
            sa.Column("action_code", sa.String(length=40), nullable=False),
            sa.Column("direction", sa.String(length=20), nullable=False),
            sa.Column("confidence", sa.Float(), nullable=True),
            sa.Column("dedupe_key", sa.String(length=64), nullable=False),
            sa.Column("inputs", sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("dedupe_key", name="uq_action_decision_dedupe"),
        )
    if op.f("ix_action_decision_snapshots_action_code") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_decision_snapshots")
    }:
        op.create_index(
            op.f("ix_action_decision_snapshots_action_code"),
            "action_decision_snapshots",
            ["action_code"],
            unique=False,
        )
    if op.f("ix_action_decision_snapshots_as_of") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_decision_snapshots")
    }:
        op.create_index(
            op.f("ix_action_decision_snapshots_as_of"),
            "action_decision_snapshots",
            ["as_of"],
            unique=False,
        )
    if op.f("ix_action_decision_snapshots_horizon") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_decision_snapshots")
    }:
        op.create_index(
            op.f("ix_action_decision_snapshots_horizon"),
            "action_decision_snapshots",
            ["horizon"],
            unique=False,
        )
    if op.f("ix_action_decision_snapshots_market") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_decision_snapshots")
    }:
        op.create_index(
            op.f("ix_action_decision_snapshots_market"),
            "action_decision_snapshots",
            ["market"],
            unique=False,
        )
    if op.f("ix_action_decision_snapshots_policy_version") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_decision_snapshots")
    }:
        op.create_index(
            op.f("ix_action_decision_snapshots_policy_version"),
            "action_decision_snapshots",
            ["policy_version"],
            unique=False,
        )
    if op.f("ix_action_decision_snapshots_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_decision_snapshots")
    }:
        op.create_index(
            op.f("ix_action_decision_snapshots_security_id"),
            "action_decision_snapshots",
            ["security_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("event_timing_revisions"):
        op.create_table(
            "event_timing_revisions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("event_id", sa.Integer(), nullable=False),
            sa.Column("payload", sa.JSON(), nullable=False),
            sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["event_id"],
                ["events.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_event_timing_revisions_event_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("event_timing_revisions")
    }:
        op.create_index(
            op.f("ix_event_timing_revisions_event_id"),
            "event_timing_revisions",
            ["event_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("market_research_snapshots"):
        op.create_table(
            "market_research_snapshots",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("payload", sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_market_research_snapshots_as_of") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("market_research_snapshots")
    }:
        op.create_index(
            op.f("ix_market_research_snapshots_as_of"),
            "market_research_snapshots",
            ["as_of"],
            unique=False,
        )
    if op.f("ix_market_research_snapshots_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("market_research_snapshots")
    }:
        op.create_index(
            op.f("ix_market_research_snapshots_security_id"),
            "market_research_snapshots",
            ["security_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("research_action_tasks"):
        op.create_table(
            "research_action_tasks",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("task_key", sa.String(length=64), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("horizon", sa.Integer(), nullable=False),
            sa.Column("kind", sa.String(length=40), nullable=False),
            sa.Column("source_kind", sa.String(length=40), nullable=False),
            sa.Column("source_id", sa.Integer(), nullable=True),
            sa.Column("source_version", sa.String(length=64), nullable=False),
            sa.Column("payload", sa.JSON(), nullable=False),
            sa.Column("status", sa.String(length=24), nullable=False),
            sa.Column("note", sa.Text(), nullable=False),
            sa.Column("expiration_reason", sa.String(length=40), nullable=False),
            sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_research_action_tasks_horizon") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_action_tasks")
    }:
        op.create_index(
            op.f("ix_research_action_tasks_horizon"),
            "research_action_tasks",
            ["horizon"],
            unique=False,
        )
    if op.f("ix_research_action_tasks_review_due_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_action_tasks")
    }:
        op.create_index(
            op.f("ix_research_action_tasks_review_due_at"),
            "research_action_tasks",
            ["review_due_at"],
            unique=False,
        )
    if op.f("ix_research_action_tasks_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_action_tasks")
    }:
        op.create_index(
            op.f("ix_research_action_tasks_security_id"),
            "research_action_tasks",
            ["security_id"],
            unique=False,
        )
    if op.f("ix_research_action_tasks_status") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_action_tasks")
    }:
        op.create_index(
            op.f("ix_research_action_tasks_status"),
            "research_action_tasks",
            ["status"],
            unique=False,
        )
    if op.f("ix_research_action_tasks_task_key") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_action_tasks")
    }:
        op.create_index(
            op.f("ix_research_action_tasks_task_key"),
            "research_action_tasks",
            ["task_key"],
            unique=True,
        )
    if not sa.inspect(bind).has_table("research_calendar_revisions"):
        op.create_table(
            "research_calendar_revisions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("fingerprint", sa.String(length=64), nullable=False),
            sa.Column("event_key", sa.String(length=160), nullable=False),
            sa.Column("revision", sa.Integer(), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=True),
            sa.Column("source", sa.String(length=80), nullable=False),
            sa.Column("source_url", sa.Text(), nullable=False),
            sa.Column("title", sa.Text(), nullable=False),
            sa.Column("event_type", sa.String(length=40), nullable=False),
            sa.Column("scheduled_date", sa.Date(), nullable=False),
            sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("timezone", sa.String(length=64), nullable=False),
            sa.Column("time_precision", sa.String(length=24), nullable=False),
            sa.Column("status", sa.String(length=24), nullable=False),
            sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("details", sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("event_key", "revision", name="uq_research_calendar_revision"),
            sa.UniqueConstraint("fingerprint"),
        )
    if op.f("ix_research_calendar_revisions_available_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_calendar_revisions")
    }:
        op.create_index(
            op.f("ix_research_calendar_revisions_available_at"),
            "research_calendar_revisions",
            ["available_at"],
            unique=False,
        )
    if op.f("ix_research_calendar_revisions_event_key") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_calendar_revisions")
    }:
        op.create_index(
            op.f("ix_research_calendar_revisions_event_key"),
            "research_calendar_revisions",
            ["event_key"],
            unique=False,
        )
    if op.f("ix_research_calendar_revisions_event_type") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_calendar_revisions")
    }:
        op.create_index(
            op.f("ix_research_calendar_revisions_event_type"),
            "research_calendar_revisions",
            ["event_type"],
            unique=False,
        )
    if op.f("ix_research_calendar_revisions_observed_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_calendar_revisions")
    }:
        op.create_index(
            op.f("ix_research_calendar_revisions_observed_at"),
            "research_calendar_revisions",
            ["observed_at"],
            unique=False,
        )
    if op.f("ix_research_calendar_revisions_scheduled_date") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_calendar_revisions")
    }:
        op.create_index(
            op.f("ix_research_calendar_revisions_scheduled_date"),
            "research_calendar_revisions",
            ["scheduled_date"],
            unique=False,
        )
    if op.f("ix_research_calendar_revisions_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_calendar_revisions")
    }:
        op.create_index(
            op.f("ix_research_calendar_revisions_security_id"),
            "research_calendar_revisions",
            ["security_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("research_disclosures"):
        op.create_table(
            "research_disclosures",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("fingerprint", sa.String(length=64), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("source", sa.String(length=80), nullable=False),
            sa.Column("source_url", sa.Text(), nullable=False),
            sa.Column("title", sa.Text(), nullable=False),
            sa.Column("form", sa.String(length=24), nullable=False),
            sa.Column("accession", sa.String(length=80), nullable=False),
            sa.Column("excerpt", sa.Text(), nullable=False),
            sa.Column("content_status", sa.String(length=24), nullable=False),
            sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("fingerprint"),
        )
    if op.f("ix_research_disclosures_available_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_disclosures")
    }:
        op.create_index(
            op.f("ix_research_disclosures_available_at"),
            "research_disclosures",
            ["available_at"],
            unique=False,
        )
    if op.f("ix_research_disclosures_observed_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_disclosures")
    }:
        op.create_index(
            op.f("ix_research_disclosures_observed_at"),
            "research_disclosures",
            ["observed_at"],
            unique=False,
        )
    if op.f("ix_research_disclosures_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_disclosures")
    }:
        op.create_index(
            op.f("ix_research_disclosures_security_id"),
            "research_disclosures",
            ["security_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("research_financial_facts"):
        op.create_table(
            "research_financial_facts",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("fingerprint", sa.String(length=64), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("source", sa.String(length=80), nullable=False),
            sa.Column("source_url", sa.Text(), nullable=False),
            sa.Column("concept", sa.String(length=160), nullable=False),
            sa.Column("value", sa.Float(), nullable=False),
            sa.Column("unit", sa.String(length=40), nullable=False),
            sa.Column("period_start", sa.Date(), nullable=True),
            sa.Column("period_end", sa.Date(), nullable=False),
            sa.Column("fiscal_period", sa.String(length=24), nullable=False),
            sa.Column("accession", sa.String(length=80), nullable=False),
            sa.Column("form", sa.String(length=24), nullable=False),
            sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("raw_data", sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("fingerprint"),
        )
    if op.f("ix_research_financial_facts_available_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_financial_facts")
    }:
        op.create_index(
            op.f("ix_research_financial_facts_available_at"),
            "research_financial_facts",
            ["available_at"],
            unique=False,
        )
    if op.f("ix_research_financial_facts_concept") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_financial_facts")
    }:
        op.create_index(
            op.f("ix_research_financial_facts_concept"),
            "research_financial_facts",
            ["concept"],
            unique=False,
        )
    if op.f("ix_research_financial_facts_observed_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_financial_facts")
    }:
        op.create_index(
            op.f("ix_research_financial_facts_observed_at"),
            "research_financial_facts",
            ["observed_at"],
            unique=False,
        )
    if op.f("ix_research_financial_facts_period_end") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_financial_facts")
    }:
        op.create_index(
            op.f("ix_research_financial_facts_period_end"),
            "research_financial_facts",
            ["period_end"],
            unique=False,
        )
    if op.f("ix_research_financial_facts_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_financial_facts")
    }:
        op.create_index(
            op.f("ix_research_financial_facts_security_id"),
            "research_financial_facts",
            ["security_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("research_source_states"):
        op.create_table(
            "research_source_states",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("source_key", sa.String(length=160), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=True),
            sa.Column("capability", sa.String(length=60), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("coverage", sa.String(length=80), nullable=False),
            sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("items_last_run", sa.Integer(), nullable=False),
            sa.Column("message", sa.Text(), nullable=False),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_research_source_states_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_source_states")
    }:
        op.create_index(
            op.f("ix_research_source_states_security_id"),
            "research_source_states",
            ["security_id"],
            unique=False,
        )
    if op.f("ix_research_source_states_source_key") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_source_states")
    }:
        op.create_index(
            op.f("ix_research_source_states_source_key"),
            "research_source_states",
            ["source_key"],
            unique=True,
        )
    if not sa.inspect(bind).has_table("security_risk_profiles"):
        op.create_table(
            "security_risk_profiles",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("current_weight", sa.Float(), nullable=True),
            sa.Column("current_quantity", sa.Float(), nullable=True),
            sa.Column("sector_current_weight", sa.Float(), nullable=True),
            sa.Column("average_cost", sa.Float(), nullable=True),
            sa.Column("max_weight", sa.Float(), nullable=True),
            sa.Column("risk_budget_pct", sa.Float(), nullable=True),
            sa.Column("stop_price", sa.Float(), nullable=True),
            sa.Column("sector_limit_pct", sa.Float(), nullable=True),
            sa.Column("lot_size", sa.Integer(), nullable=True),
            sa.Column("max_participation_pct", sa.Float(), nullable=True),
            sa.Column("fee_bps", sa.Float(), nullable=True),
            sa.Column("slippage_bps", sa.Float(), nullable=True),
            sa.Column("benchmark_market", sa.String(length=8), nullable=True),
            sa.Column("benchmark_symbol", sa.String(length=24), nullable=True),
            sa.Column("benchmark_currency", sa.String(length=8), nullable=True),
            sa.Column("benchmark_label", sa.String(length=160), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["security_id"], ["securities.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_security_risk_profiles_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("security_risk_profiles")
    }:
        op.create_index(
            op.f("ix_security_risk_profiles_security_id"),
            "security_risk_profiles",
            ["security_id"],
            unique=True,
        )
    if not sa.inspect(bind).has_table("action_evaluation_results"):
        op.create_table(
            "action_evaluation_results",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("snapshot_id", sa.Integer(), nullable=False),
            sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("payload", sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(
                ["snapshot_id"], ["action_decision_snapshots.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_action_evaluation_results_snapshot_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("action_evaluation_results")
    }:
        op.create_index(
            op.f("ix_action_evaluation_results_snapshot_id"),
            "action_evaluation_results",
            ["snapshot_id"],
            unique=True,
        )
    if not sa.inspect(bind).has_table("research_action_task_history"):
        op.create_table(
            "research_action_task_history",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("task_id", sa.Integer(), nullable=False),
            sa.Column("from_status", sa.String(length=24), nullable=True),
            sa.Column("to_status", sa.String(length=24), nullable=False),
            sa.Column("reason", sa.String(length=64), nullable=False),
            sa.Column("note", sa.Text(), nullable=False),
            sa.Column("snapshot", sa.JSON(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["task_id"], ["research_action_tasks.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_research_action_task_history_task_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_action_task_history")
    }:
        op.create_index(
            op.f("ix_research_action_task_history_task_id"),
            "research_action_task_history",
            ["task_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("research_expectations"):
        op.create_table(
            "research_expectations",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("fingerprint", sa.String(length=64), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("event_key", sa.String(length=160), nullable=False),
            sa.Column("calendar_revision_id", sa.Integer(), nullable=False),
            sa.Column("metric", sa.String(length=80), nullable=False),
            sa.Column("value", sa.Float(), nullable=False),
            sa.Column("unit", sa.String(length=40), nullable=False),
            sa.Column("source", sa.String(length=80), nullable=False),
            sa.Column("financial_period", sa.String(length=64), nullable=False, server_default=""),
            sa.Column("expected_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("source_url", sa.Text(), nullable=False),
            sa.Column("estimate_kind", sa.String(length=40), nullable=False),
            sa.Column("is_pre_release", sa.Boolean(), nullable=False),
            sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["calendar_revision_id"],
                ["research_calendar_revisions.id"],
            ),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("fingerprint"),
        )
    if op.f("ix_research_expectations_available_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_expectations")
    }:
        op.create_index(
            op.f("ix_research_expectations_available_at"),
            "research_expectations",
            ["available_at"],
            unique=False,
        )
    if op.f("ix_research_expectations_event_key") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_expectations")
    }:
        op.create_index(
            op.f("ix_research_expectations_event_key"),
            "research_expectations",
            ["event_key"],
            unique=False,
        )
    if op.f("ix_research_expectations_observed_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_expectations")
    }:
        op.create_index(
            op.f("ix_research_expectations_observed_at"),
            "research_expectations",
            ["observed_at"],
            unique=False,
        )
    if op.f("ix_research_expectations_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("research_expectations")
    }:
        op.create_index(
            op.f("ix_research_expectations_security_id"),
            "research_expectations",
            ["security_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("x_research_claims"):
        op.create_table(
            "x_research_claims",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("claim_key", sa.String(length=64), nullable=False),
            sa.Column("post_id", sa.Integer(), nullable=True),
            sa.Column("author", sa.String(length=64), nullable=False),
            sa.Column("post_url", sa.Text(), nullable=False),
            sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("claim_text", sa.Text(), nullable=False),
            sa.Column("claim_kind", sa.String(length=32), nullable=False),
            sa.Column("verification_needs", sa.JSON(), nullable=False),
            sa.Column("source_truncated", sa.Boolean(), nullable=False),
            sa.Column("source_version", sa.String(length=64), nullable=False),
            sa.Column("source_snapshot", sa.JSON(), nullable=False),
            sa.Column("status", sa.String(length=24), nullable=False),
            sa.Column("note", sa.Text(), nullable=False),
            sa.Column("expiration_reason", sa.String(length=40), nullable=False),
            sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["post_id"], ["x_posts.id"], ondelete="SET NULL"),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_x_research_claims_claim_key") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claims")
    }:
        op.create_index(
            op.f("ix_x_research_claims_claim_key"), "x_research_claims", ["claim_key"], unique=True
        )
    if op.f("ix_x_research_claims_post_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claims")
    }:
        op.create_index(
            op.f("ix_x_research_claims_post_id"), "x_research_claims", ["post_id"], unique=False
        )
    if op.f("ix_x_research_claims_published_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claims")
    }:
        op.create_index(
            op.f("ix_x_research_claims_published_at"),
            "x_research_claims",
            ["published_at"],
            unique=False,
        )
    if op.f("ix_x_research_claims_review_due_at") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claims")
    }:
        op.create_index(
            op.f("ix_x_research_claims_review_due_at"),
            "x_research_claims",
            ["review_due_at"],
            unique=False,
        )
    if op.f("ix_x_research_claims_status") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claims")
    }:
        op.create_index(
            op.f("ix_x_research_claims_status"), "x_research_claims", ["status"], unique=False
        )
    if not sa.inspect(bind).has_table("x_research_claim_evidence"):
        op.create_table(
            "x_research_claim_evidence",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("claim_id", sa.Integer(), nullable=False),
            sa.Column("url", sa.Text(), nullable=False),
            sa.Column("source_url", sa.Text(), nullable=False),
            sa.Column("source_key", sa.String(length=64), nullable=False),
            sa.Column("stance", sa.String(length=20), nullable=False),
            sa.Column("is_official", sa.Boolean(), nullable=False),
            sa.Column("note", sa.Text(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["claim_id"], ["x_research_claims.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "claim_id", "source_key", "stance", name="uq_x_claim_evidence_source"
            ),
        )
    if op.f("ix_x_research_claim_evidence_claim_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claim_evidence")
    }:
        op.create_index(
            op.f("ix_x_research_claim_evidence_claim_id"),
            "x_research_claim_evidence",
            ["claim_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("x_research_claim_history"):
        op.create_table(
            "x_research_claim_history",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("claim_id", sa.Integer(), nullable=False),
            sa.Column("from_status", sa.String(length=24), nullable=True),
            sa.Column("to_status", sa.String(length=24), nullable=False),
            sa.Column("reason", sa.String(length=64), nullable=False),
            sa.Column("note", sa.Text(), nullable=False),
            sa.Column("snapshot", sa.JSON(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["claim_id"], ["x_research_claims.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
    if op.f("ix_x_research_claim_history_claim_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claim_history")
    }:
        op.create_index(
            op.f("ix_x_research_claim_history_claim_id"),
            "x_research_claim_history",
            ["claim_id"],
            unique=False,
        )
    if not sa.inspect(bind).has_table("x_research_claim_securities"):
        op.create_table(
            "x_research_claim_securities",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("claim_id", sa.Integer(), nullable=False),
            sa.Column("security_id", sa.Integer(), nullable=False),
            sa.Column("match_basis", sa.String(length=20), nullable=False),
            sa.ForeignKeyConstraint(["claim_id"], ["x_research_claims.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(
                ["security_id"],
                ["securities.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("claim_id", "security_id", name="uq_x_claim_security"),
        )
    if op.f("ix_x_research_claim_securities_claim_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claim_securities")
    }:
        op.create_index(
            op.f("ix_x_research_claim_securities_claim_id"),
            "x_research_claim_securities",
            ["claim_id"],
            unique=False,
        )
    if op.f("ix_x_research_claim_securities_security_id") not in {
        i["name"] for i in sa.inspect(bind).get_indexes("x_research_claim_securities")
    }:
        op.create_index(
            op.f("ix_x_research_claim_securities_security_id"),
            "x_research_claim_securities",
            ["security_id"],
            unique=False,
        )
    # Also cover tables created by a development app before Alembic ran.
    additions = {
        "research_expectations": (
            sa.Column("financial_period", sa.String(64), nullable=False, server_default=""),
            sa.Column("expected_at", sa.DateTime(timezone=True), nullable=True),
        ),
        "portfolio_risk_profiles": (sa.Column("available_cash", sa.Float(), nullable=True),),
        "security_risk_profiles": (
            sa.Column("current_quantity", sa.Float(), nullable=True),
            sa.Column("sector_current_weight", sa.Float(), nullable=True),
        ),
    }
    for table_name, desired in additions.items():
        existing = {column["name"] for column in sa.inspect(bind).get_columns(table_name)}
        for column in desired:
            if column.name not in existing:
                op.add_column(table_name, column)
    if not sa.inspect(bind).has_table("macro_observation_vintages"):
        op.create_table(
            "macro_observation_vintages",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("fingerprint", sa.String(64), nullable=False, unique=True),
            sa.Column("series", sa.String(80), nullable=False),
            sa.Column("period", sa.String(20), nullable=False),
            sa.Column("value", sa.Float(), nullable=False),
            sa.Column("unit", sa.String(40), nullable=False),
            sa.Column("source_url", sa.Text(), nullable=False),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("metadata_values", sa.JSON(), nullable=False),
        )
        op.create_index(
            "ix_macro_observation_vintages_series", "macro_observation_vintages", ["series"]
        )
        op.create_index(
            "ix_macro_observation_vintages_period", "macro_observation_vintages", ["period"]
        )


def downgrade() -> None:
    bind = op.get_bind()
    if sa.inspect(bind).has_table("macro_observation_vintages"):
        op.drop_table("macro_observation_vintages")
    if sa.inspect(bind).has_table("x_research_claim_securities"):
        op.drop_table("x_research_claim_securities")
    if sa.inspect(bind).has_table("x_research_claim_history"):
        op.drop_table("x_research_claim_history")
    if sa.inspect(bind).has_table("x_research_claim_evidence"):
        op.drop_table("x_research_claim_evidence")
    if sa.inspect(bind).has_table("x_research_claims"):
        op.drop_table("x_research_claims")
    if sa.inspect(bind).has_table("research_expectations"):
        op.drop_table("research_expectations")
    if sa.inspect(bind).has_table("research_action_task_history"):
        op.drop_table("research_action_task_history")
    if sa.inspect(bind).has_table("action_evaluation_results"):
        op.drop_table("action_evaluation_results")
    if sa.inspect(bind).has_table("security_risk_profiles"):
        op.drop_table("security_risk_profiles")
    if sa.inspect(bind).has_table("research_source_states"):
        op.drop_table("research_source_states")
    if sa.inspect(bind).has_table("research_financial_facts"):
        op.drop_table("research_financial_facts")
    if sa.inspect(bind).has_table("research_disclosures"):
        op.drop_table("research_disclosures")
    if sa.inspect(bind).has_table("research_calendar_revisions"):
        op.drop_table("research_calendar_revisions")
    if sa.inspect(bind).has_table("research_action_tasks"):
        op.drop_table("research_action_tasks")
    if sa.inspect(bind).has_table("market_research_snapshots"):
        op.drop_table("market_research_snapshots")
    if sa.inspect(bind).has_table("event_timing_revisions"):
        op.drop_table("event_timing_revisions")
    if sa.inspect(bind).has_table("action_decision_snapshots"):
        op.drop_table("action_decision_snapshots")
    if sa.inspect(bind).has_table("portfolio_risk_profiles"):
        op.drop_table("portfolio_risk_profiles")
    with op.batch_alter_table("events") as batch:
        for name in (
            "first_disclosed_at",
            "fact_time_verified",
            "financial_period",
            "fact_source_url",
        ):
            batch.drop_column(name)
